// Imported from avdbapi-details(1).json. Card-facing metadata only; descriptions are intentionally kept out of the grid.
window.AVDB_IMPORTED_MOVIES = [
  {
    "id": "avdb-613139",
    "sourceId": "613139",
    "type": "series",
    "label": "Series",
    "title": "JD067 - Wrong bridal sedan, right groom [Part 2]",
    "code": "JD067",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/JD067/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/JD067/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/b038f5511fd3",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "jd067",
    "addedAt": "2026-08-09 17:26:47",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=613139"
  },
  {
    "id": "avdb-613153",
    "sourceId": "613153",
    "type": "movie",
    "label": "Movie",
    "title": "MDX0146 - Purifying dirty energy with passionate dual cultivation: Down-and-out girl reverses fate through sex",
    "code": "MDX0146",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/MDX0146/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/MDX0146/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/69f730b3e7ca",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "mdx0146",
    "addedAt": "2026-08-09 17:25:09",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=613153"
  },
  {
    "id": "avdb-613152",
    "sourceId": "613152",
    "type": "movie",
    "label": "Movie",
    "title": "MAD019 - Gone with the Wind Chapter 3: Female officer’s seductive secret order",
    "code": "MAD019",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/MAD019/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/MAD019/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/89cbb2da336f",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "mad019",
    "addedAt": "2026-08-09 17:23:36",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=613152"
  },
  {
    "id": "avdb-613151",
    "sourceId": "613151",
    "type": "series",
    "label": "Series",
    "title": "JDMY010 - Close friends [EP10]",
    "code": "JDMY010",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/JDMY010/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/JDMY010/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/7c365f768d5c",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "jdmy010",
    "addedAt": "2026-08-09 17:22:25",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=613151"
  },
  {
    "id": "avdb-613150",
    "sourceId": "613150",
    "type": "series",
    "label": "Series",
    "title": "JDMY009 - Close friends [EP9]",
    "code": "JDMY009",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/JDMY009/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/JDMY009/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/5c692b9b62f7",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "jdmy009",
    "addedAt": "2026-08-09 17:21:16",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=613150"
  },
  {
    "id": "avdb-613149",
    "sourceId": "613149",
    "type": "series",
    "label": "Series",
    "title": "JDMY008 - Close friends [EP8]",
    "code": "JDMY008",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/JDMY008/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/JDMY008/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/74e1af65f6de",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "jdmy008",
    "addedAt": "2026-08-09 17:20:14",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=613149"
  },
  {
    "id": "avdb-613148",
    "sourceId": "613148",
    "type": "series",
    "label": "Series",
    "title": "JDMY007 - Close friends [EP7]",
    "code": "JDMY007",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/JDMY007/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/JDMY007/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/cbfa64a1d548",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "jdmy007",
    "addedAt": "2026-08-09 17:18:55",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=613148"
  },
  {
    "id": "avdb-613147",
    "sourceId": "613147",
    "type": "series",
    "label": "Series",
    "title": "JDMY006 - Close friends [EP6]",
    "code": "JDMY006",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/JDMY006/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/JDMY006/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/4a1c0edb6c95",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "jdmy006",
    "addedAt": "2026-08-09 17:16:58",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=613147"
  },
  {
    "id": "avdb-613146",
    "sourceId": "613146",
    "type": "series",
    "label": "Series",
    "title": "JDMY005 - Close friends [EP5]",
    "code": "JDMY005",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/JDMY005/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/JDMY005/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/66948354c906",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "jdmy005",
    "addedAt": "2026-08-09 17:15:54",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=613146"
  },
  {
    "id": "avdb-613145",
    "sourceId": "613145",
    "type": "series",
    "label": "Series",
    "title": "JDMY004 - Close friends [EP4]",
    "code": "JDMY004",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/JDMY004/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/JDMY004/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/a9b919539446",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "jdmy004",
    "addedAt": "2026-08-09 17:14:35",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=613145"
  },
  {
    "id": "avdb-613144",
    "sourceId": "613144",
    "type": "series",
    "label": "Series",
    "title": "JDMY003 - Close friends [EP3]",
    "code": "jdmy003",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/JDMY003/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/JDMY003/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/d5aa1df37990",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "JDMY003",
    "addedAt": "2026-08-09 17:13:51",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=613144"
  },
  {
    "id": "avdb-613143",
    "sourceId": "613143",
    "type": "series",
    "label": "Series",
    "title": "JDMY002 - Close friends [EP2]",
    "code": "JDMY002",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/JDMY002/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/JDMY002/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/a1f340aad021",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "jdmy002",
    "addedAt": "2026-08-09 17:12:29",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=613143"
  },
  {
    "id": "avdb-613141",
    "sourceId": "613141",
    "type": "series",
    "label": "Series",
    "title": "JDMY001 - Close friends [EP1]",
    "code": "JDMY001",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/JDMY001/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/JDMY001/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/ebe3e1b5b2cb",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "jdmy001",
    "addedAt": "2026-08-09 17:11:21",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=613141"
  },
  {
    "id": "avdb-613140",
    "sourceId": "613140",
    "type": "movie",
    "label": "Movie",
    "title": "JD068 - Naked agent",
    "code": "JD068",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/JD068/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/JD068/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/74ac876e6b0d",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "jd068",
    "addedAt": "2026-08-09 17:10:03",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=613140"
  },
  {
    "id": "avdb-613138",
    "sourceId": "613138",
    "type": "movie",
    "label": "Movie",
    "title": "MMZ024 - My twisted love with brother-in-law: Secret forced sex game",
    "code": "MMZ024",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/MMZ024/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/MMZ024/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/d38904620091",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "mmz024",
    "addedAt": "2026-08-09 17:07:10",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=613138"
  },
  {
    "id": "avdb-613137",
    "sourceId": "613137",
    "type": "series",
    "label": "Series",
    "title": "JDMY010 - Close friends [EP10]",
    "code": "JDMY010",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/JDMY010/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/JDMY010/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/7c365f768d5c",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "jdmy010",
    "addedAt": "2026-08-09 17:04:47",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=613137"
  },
  {
    "id": "avdb-613135",
    "sourceId": "613135",
    "type": "movie",
    "label": "Movie",
    "title": "MSM004 - Sisters and boyfriend",
    "code": "MSM004",
    "meta": "2021 · Chinese AV",
    "year": 2021,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/MSM004/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/MSM004/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/019d055d43f9",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "msm004",
    "addedAt": "2026-08-09 17:01:52",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=613135"
  },
  {
    "id": "avdb-612806",
    "sourceId": "612806",
    "type": "movie",
    "label": "Movie",
    "title": "XK8075 - Infernal Affairs final chapter: Ultimate Infernal",
    "code": "XK8075",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/XK8075/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/XK8075/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/e6e2f17d2ebd",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "xk8075",
    "addedAt": "2026-08-09 11:26:40",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=612806"
  },
  {
    "id": "avdb-612804",
    "sourceId": "612804",
    "type": "series",
    "label": "Series",
    "title": "XK8076 - Stalking [Part 1] Slut edition",
    "code": "XK8076",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/XK8076/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/XK8076/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/ae70d5b67674",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "xk8076",
    "addedAt": "2026-08-09 11:26:27",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=612804"
  },
  {
    "id": "avdb-612790",
    "sourceId": "612790",
    "type": "movie",
    "label": "Movie",
    "title": "RAS0102 - NTR sister threesome: High school girls’ temptation",
    "code": "RAS0102",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/RAS0102/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/RAS0102/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/db0ac5266445",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "ras0102",
    "addedAt": "2026-08-09 11:26:19",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=612790"
  },
  {
    "id": "avdb-612786",
    "sourceId": "612786",
    "type": "series",
    "label": "Series",
    "title": "JD067 - Wrong bridal sedan, right groom [Part 2]",
    "code": "JD067",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/JD067/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/JD067/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/b038f5511fd3",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "jd067",
    "addedAt": "2026-08-09 11:25:46",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=612786"
  },
  {
    "id": "avdb-612345",
    "sourceId": "612345",
    "type": "series",
    "label": "Series",
    "title": "SQGY01 - Erotic Apartment [EP1]: Guangu miraculously enters the thief’s den",
    "code": "SQGY01",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/SQGY01/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/SQGY01/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/4d8f0c6505b5",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "sqgy01",
    "addedAt": "2026-08-09 11:25:35",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=612345"
  },
  {
    "id": "avdb-612347",
    "sourceId": "612347",
    "type": "series",
    "label": "Series",
    "title": "SQGY02 - Erotic Apartment [EP2]: Green-hat Joe turns the tables",
    "code": "SQGY02",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/SQGY02/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/SQGY02/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/aa642cf7e4e4",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "sqgy02",
    "addedAt": "2026-08-09 11:25:24",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=612347"
  },
  {
    "id": "avdb-612340",
    "sourceId": "612340",
    "type": "series",
    "label": "Series",
    "title": "MTVQ10EP1 - Madou variety: Hello Neighbor [EP1]",
    "code": "MTVQ10EP1",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/MTVQ10EP1/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/MTVQ10EP1/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/06cbd903c131",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "mtvq10",
    "addedAt": "2026-08-09 11:24:30",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=612340"
  },
  {
    "id": "avdb-612342",
    "sourceId": "612342",
    "type": "movie",
    "label": "Movie",
    "title": "RAS0063 - Delinquent boy molests on the train: Strict female teacher’s shameful development",
    "code": "RAS0063",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/RAS0063/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/RAS0063/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/eb4f06567681",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "ras0063",
    "addedAt": "2026-08-09 11:24:20",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=612342"
  },
  {
    "id": "avdb-612338",
    "sourceId": "612338",
    "type": "series",
    "label": "Series",
    "title": "MDX149 (1) - Fulfilling the Doraemon AV dream (Part 1): Nobita peeks at Shizuka’s beautiful body, awakens beastly lust and forces her",
    "code": "MDX149",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/MDX149/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/MDX149/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/cfeb6ce9911c",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "mdx149",
    "addedAt": "2026-08-09 11:24:11",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=612338"
  },
  {
    "id": "avdb-612337",
    "sourceId": "612337",
    "type": "movie",
    "label": "Movie",
    "title": "MD178 - Slutty trainee desperately seeks sex: Coach’s beastly lust must be obeyed",
    "code": "MD178",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/MD178/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/MD178/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/74c1df19a1ee",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "md178",
    "addedAt": "2026-08-09 11:24:02",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=612337"
  },
  {
    "id": "avdb-612333",
    "sourceId": "612333",
    "type": "movie",
    "label": "Movie",
    "title": "D070 / JD070 - Never would have thought: Legend of the White Snake",
    "code": "D070",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/D070/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/D070/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/03f0425c2fe5",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "d070",
    "addedAt": "2026-08-09 11:23:53",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=612333"
  },
  {
    "id": "avdb-612330",
    "sourceId": "612330",
    "type": "movie",
    "label": "Movie",
    "title": "HPP0013 - Alpha car sex: Super intense first-experience interview ends in passionate car sex on a luxury car",
    "code": "HPP0013",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/HPP0013/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/HPP0013/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/6c15ec2cbcdb",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "hpp0013",
    "addedAt": "2026-08-09 11:23:43",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=612330"
  },
  {
    "id": "avdb-612327",
    "sourceId": "612327",
    "type": "movie",
    "label": "Movie",
    "title": "XK8070 - Lustful snake",
    "code": "XK8070",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/XK8070/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/XK8070/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/47b14984dbdd",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "xk8070",
    "addedAt": "2026-08-09 11:23:34",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=612327"
  },
  {
    "id": "avdb-612325",
    "sourceId": "612325",
    "type": "movie",
    "label": "Movie",
    "title": "TM0128 - Slutty agent’s special sales: Fucking the slutty agent next to the wife",
    "code": "TM0128",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/TM0128/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/TM0128/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/0fe4694b928d",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "tm0128",
    "addedAt": "2026-08-09 11:23:23",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=612325"
  },
  {
    "id": "avdb-612323",
    "sourceId": "612323",
    "type": "movie",
    "label": "Movie",
    "title": "TM0126 - Dark Child Annie: Tibbers uses his big cock to expel Annie’s lust mushroom toxin",
    "code": "TM0126",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/TM0126/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/TM0126/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/ac2eade5c12e",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "tm0126",
    "addedAt": "2026-08-09 11:23:11",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=612323"
  },
  {
    "id": "avdb-612321",
    "sourceId": "612321",
    "type": "movie",
    "label": "Movie",
    "title": "JD069 - Forcing the student’s beautiful sister: When a hot older sister meets a scumbag teacher",
    "code": "JD069",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/JD069/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/JD069/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/00798fc2b26b",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "jd069",
    "addedAt": "2026-08-09 11:22:58",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=612321"
  },
  {
    "id": "avdb-612319",
    "sourceId": "612319",
    "type": "series",
    "label": "Series",
    "title": "JD066 - Wrong bridal sedan, right groom [Part 1]",
    "code": "JD066",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/JD066/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/JD066/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/eacf80ce66d6",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "jd066",
    "addedAt": "2026-08-09 11:22:48",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=612319"
  },
  {
    "id": "avdb-612317",
    "sourceId": "612317",
    "type": "movie",
    "label": "Movie",
    "title": "XK8069 - My wife is a big boss",
    "code": "XK8069",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/XK8069/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/XK8069/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/949f6207ddd8",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "xk8069",
    "addedAt": "2026-08-09 11:22:40",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=612317"
  },
  {
    "id": "avdb-612315",
    "sourceId": "612315",
    "type": "movie",
    "label": "Movie",
    "title": "XK8067 - Programmer’s fantasy journey",
    "code": "XK8067",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/XK8067/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/XK8067/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/79d795beda8d",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "xk8067",
    "addedAt": "2026-08-09 11:22:31",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=612315"
  },
  {
    "id": "avdb-612312",
    "sourceId": "612312",
    "type": "movie",
    "label": "Movie",
    "title": "XK8049 - My little sister has grown up: Brother-sister intimacy tutorial – Qian Ling",
    "code": "XK8049",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/XK8049/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/XK8049/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/4028075bf6a9",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "xk8049",
    "addedAt": "2026-08-09 11:22:21",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=612312"
  },
  {
    "id": "avdb-612309",
    "sourceId": "612309",
    "type": "movie",
    "label": "Movie",
    "title": "TM0127 - Ultimate slutty nurse: The white-coat angel is actually a sex-crazed nympho",
    "code": "TM0127",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/TM0127/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/TM0127/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/a4d4b2f5ed3a",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "tm0127",
    "addedAt": "2026-08-09 11:22:11",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=612309"
  },
  {
    "id": "avdb-612308",
    "sourceId": "612308",
    "type": "series",
    "label": "Series",
    "title": "TM0107 - Ghost father [Part 1] Naughty panties",
    "code": "TM0107",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/TM0107/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/TM0107/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/c010603ee7bb",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "tm0107",
    "addedAt": "2026-08-09 11:22:01",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=612308"
  },
  {
    "id": "avdb-612304",
    "sourceId": "612304",
    "type": "movie",
    "label": "Movie",
    "title": "RAS098 - Boss violates the wronged subordinate",
    "code": "RAS098",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/RAS098/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/RAS098/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/63cecd2aad79",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "ras098",
    "addedAt": "2026-08-09 11:21:46",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=612304"
  },
  {
    "id": "avdb-612303",
    "sourceId": "612303",
    "type": "movie",
    "label": "Movie",
    "title": "RAS087 - Goddess after breakup begs me to fuck her and soothe the pain with my cock",
    "code": "RAS087",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/RAS087/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/RAS087/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/cee2a00cca39",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "ras087",
    "addedAt": "2026-08-09 11:21:02",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=612303"
  },
  {
    "id": "avdb-612166",
    "sourceId": "612166",
    "type": "movie",
    "label": "Movie",
    "title": "JD065 - Northeast past: White tiger",
    "code": "JD065",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/JD065/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/JD065/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/dec1fd7a3224",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "jd065",
    "addedAt": "2026-08-09 11:20:51",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=612166"
  },
  {
    "id": "avdb-612162",
    "sourceId": "612162",
    "type": "movie",
    "label": "Movie",
    "title": "JD063 Fitness Sex: Coach’s big dick poked me and made my pussy wet",
    "code": "JD063",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/JD063/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/JD063/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/86ad3ce1e98b",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "jd063",
    "addedAt": "2026-08-09 11:20:41",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=612162"
  },
  {
    "id": "avdb-611398",
    "sourceId": "611398",
    "type": "movie",
    "label": "Movie",
    "title": "JD064 - Chang’e Flying to the Moon",
    "code": "JD064",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/JD064/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/JD064/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/abfa20a37388",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "jd064",
    "addedAt": "2026-08-09 11:20:30",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=611398"
  },
  {
    "id": "avdb-611396",
    "sourceId": "611396",
    "type": "movie",
    "label": "Movie",
    "title": "JD062 - Northeast Past: Immortal Jump (仙人跳)",
    "code": "JD062",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/JD062/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/JD062/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/6dad7321ad69",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "jd062",
    "addedAt": "2026-08-09 11:20:20",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=611396"
  },
  {
    "id": "avdb-611395",
    "sourceId": "611395",
    "type": "movie",
    "label": "Movie",
    "title": "XK8066 - Simp Diary: Mistaking the Simp for a King and Turning the Mistake into a Dream Come True",
    "code": "XK8066",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/XK8066/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/XK8066/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/d543067def4b",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "xk8066",
    "addedAt": "2026-08-09 11:20:09",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=611395"
  },
  {
    "id": "avdb-611387",
    "sourceId": "611387",
    "type": "movie",
    "label": "Movie",
    "title": "TM0124 - Gorgeous Mother [3]: Framed Married Woman",
    "code": "TM0124",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/TM0124/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/TM0124/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/7b1adb47a41c",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "tm0124",
    "addedAt": "2026-08-09 11:19:57",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=611387"
  },
  {
    "id": "avdb-611384",
    "sourceId": "611384",
    "type": "movie",
    "label": "Movie",
    "title": "XK8064 - Girlfriend’s Secret: Bathroom Affair Lover Turns Out to Be Boyfriend’s Dad",
    "code": "XK8064",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/XK8064/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/XK8064/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/6845351baae7",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "xk8064",
    "addedAt": "2026-08-09 11:19:16",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=611384"
  },
  {
    "id": "avdb-611383",
    "sourceId": "611383",
    "type": "movie",
    "label": "Movie",
    "title": "RAS099 - Sex Subway: Men-Only Carriage",
    "code": "RAS099",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/RAS099/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/RAS099/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/5bc40fbeaee4",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "ras099",
    "addedAt": "2026-08-09 11:18:42",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=611383"
  },
  {
    "id": "avdb-611378",
    "sourceId": "611378",
    "type": "movie",
    "label": "Movie",
    "title": "TM0123 - Perverted Father & Daughter: Rebellious Girl Forced into Double Penetration by Her Twisted Father",
    "code": "TM0123",
    "meta": "2026 · Chinese AV",
    "year": 2026,
    "genre": "Chinese AV",
    "status": "ready",
    "visible": true,
    "posterUrl": "https://upload18.cc/v/TM0123/poster.jpg",
    "thumbUrl": "https://upload18.cc/v/TM0123/poster.jpg",
    "playerUrl": "https://upload18.org/play/index/6e306dfdae82",
    "playerOrigin": "https://upload18.org",
    "playerReferer": "https://upload18.org/",
    "playerUserAgent": "",
    "slug": "tm0123",
    "addedAt": "2026-08-09 11:18:24",
    "sourceUrl": "https://avdbapi.com/api.php/provide/vod?ac=detail&ids=611378"
  }
];
